In [166]:
import numpy as np 
import os
import csv
import timeit

def load_data(data_path):
    """
    Associated test case: tests/test_data.py

    Reading and manipulating data is a vital skill for machine learning.

    This function loads the data in data_path csv into two numpy arrays:
    features (of size NxK) and targets (of size Nx1) where N is the number of rows
    and K is the number of features. 
    
    data_path leads to a csv comma-delimited file with each row corresponding to a 
    different example. Each row contains binary features for each example 
    (e.g. chocolate, fruity, caramel, etc.) The last column indicates the label for the
    example how likely it is to win a head-to-head matchup with another candy 
    bar.

    This function reads in the csv file, and reads each row into two numpy arrays.
    The first array contains the features for each row. For example, in candy-data.csv
    the features are:

    chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus

    The second array contains the targets for each row. The targets are in the last 
    column of the csv file (labeled 'class'). The first row of the csv file contains 
    the labels for each column and shouldn't be read into an array.

    Example:
    chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,class
    1,0,1,0,0,1,0,1,0,1

    should be turned into:

    [1,0,1,0,0,1,0,1,0] (features) and [1] (targets).

    This should be done for each row in the csv file, making arrays of size NxK and Nx1.

    Args:
        data_path (str): path to csv file containing the data

    Output:
        features (np.array): numpy array of size NxK containing the K features
        targets (np.array): numpy array of size 1xN containing the N targets.
        attribute_names (list): list of strings containing names of each attribute 
            (headers of csv)
    """

    with open(data_path, 'r', newline = '') as csvfile:
        data = csv.reader(csvfile, delimiter = ',')
        attribute_names = data.__next__()

        col_len = len(attribute_names) - 1 # Number of features
    
        attribute_names = attribute_names[:-1]
        features = list()
        targets = list()
    
        for row in data:
            features.append([float(el) for el in row[:col_len]]) 
            targets.append(int(row[col_len]))
        
    return np.array(features), np.array(targets), attribute_names

In [167]:
data_path = './data/candy-data.csv'
data = load_data(data_path)[0]

In [168]:
import random

# data = np.array(list(range(5,25)))


test_ind = random.sample(range(data.shape[0]), 5)
test_ind

[76, 46, 50, 38, 35]

In [169]:
data[test_ind]

array([[1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 1.]])

In [171]:
train_ind = list(set(range(data.shape[0])) - set(test_ind))

In [173]:
data[train_ind]

array([[1., 0., 1., 0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 1., 1., 1., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [1.

In [ ]:
da

In [187]:
actual = np.array([1,1,1,0])
pred = np.array([0,1,1,0])

In [189]:
from sklearn.metrics import confusion_matrix

array([[1, 0],
       [1, 2]])

In [203]:
conf_m = confusion_matrix(actual, pred)
precision = conf_m[1,1] / sum(conf_m[:,1])
recall = conf_m[1,1] / sum(conf_m[:,1])

In [204]:
precision

1.0

In [230]:
def prior_proba(targets:np.array, class_:float):

    return sum(targets==class_)/len(targets)

def entropy(features, targets):

    # entropy = 0 for entirely homogeneous nodes i.e. nodes with just 1 class
    if len(list(set(targets))) == 1:
        return 0

    return sum([ -prior_proba(targets, class_) * np.log2(prior_proba(targets, class_))  for class_ in list(set(targets))])

In [240]:
arr = np.array([1,1,1,1,1,1,1,1,1,1])
sum(arr == 0)

0

In [241]:

entropy([1], arr)

0

In [265]:
def prior_proba(targets:np.array, class_:float):

    return sum(targets==class_)/len(targets)

def entropy(targets):

    # entropy = 0 for entirely homogeneous nodes i.e. nodes with just 1 class
    if len(list(set(targets))) == 1:
        return 0

    return sum([ -prior_proba(targets, class_) * np.log2(prior_proba(targets, class_))  for class_ in list(set(targets))])

def information_gain(features, attribute_index, targets):
    """
    TODO: Implement me!

    Information gain is how a decision tree makes decisions on how to create
    split points in the tree. Information gain is measured in terms of entropy.
    The goal of a decision tree is to decrease entropy at each split point as much as
    possible. This function should work perfectly or your decision tree will not work
    properly.

    Information gain is a central concept in many machine learning algorithms. In
    decision trees, it captures how effective splitting the tree on a specific attribute
    will be for the goal of classifying the training data correctly. Consider
    data points S and an attribute A. S is split into two data points given binary A:

        S(A == 0) and S(A == 1)

    Together, the two subsets make up S. If A was an attribute perfectly correlated with
    the class of each data point in S, then all points in a given subset will have the
    same class. Clearly, in this case, we want something that captures that A is a good
    attribute to use in the decision tree. This something is information gain. Formally:

        IG(S,A) = H(S) - H(S|A)

    where H is information entropy. Recall that entropy captures how orderly or chaotic
    a system is. A system that is very chaotic will evenly distribute probabilities to
    all outcomes (e.g. 50% chance of class 0, 50% chance of class 1). Machine learning
    algorithms work to decrease entropy, as that is the only way to make predictions
    that are accurate on testing data. Formally, H is defined as:

        H(S) = sum_{c in (classes in S)} -p(c) * log_2 p(c)

    To elaborate: for each class in S, you compute its prior probability p(c):

        (# of elements of class c in S) / (total # of elements in S)

    Then you compute the term for this class:

        -p(c) * log_2 p(c)

    Then compute the sum across all classes. The final number is the entropy. To gain
    more intution about entropy, consider the following - what does H(S) = 0 tell you
    about S?

    Information gain is an extension of entropy. The equation for information gain
    involves comparing the entropy of the set and the entropy of the set when conditioned
    on selecting for a single attribute (e.g. S(A == 0)).

    For more details: https://en.wikipedia.org/wiki/ID3_algorithm#The_ID3_metrics

    Args:
        features (np.array): numpy array containing features for each example.
        attribute_index (int): which column of features to take when computing the
            information gain
        targets (np.array): numpy array containing labels corresponding to each example.

    Output:
        information_gain (float): information gain if the features were split on the
            attribute_index.
    """

    parent_entropy = entropy(targets=targets)

    feature_classes = list(set(features[:,attribute_index]))

    # if the selected feature has only 1 class in it, then it will not separate anything
    # i.e. it will not give any information
    if len(feature_classes) == 1:
        return 0


    child_entropies = [(sum(features[:,attribute_index]==feature_class) / len(targets)) * entropy(targets[features[:,attribute_index]==feature_class]) for feature_class in feature_classes]

    split_entropy = sum(child_entropies)

    return parent_entropy - split_entropy

In [269]:
targets = np.array([1,0,1,0])
features = np.array([[1,1],[1,0],[0,1], [1,0]])

information_gain(features, 0, targets)

0.31127812445913283

In [249]:
targets[features[:,0] == 1]

array([1, 0, 0])

In [268]:
1 - ((-np.log2(2/3) * 2/3 - 1/3 * np.log2(1/3)) * 3/4 + 1/4 * 0)

0.31127812445913283

In [251]:
sum(features[:,0] == 1)

3

In [184]:
actual == 0

array([False, False, False,  True])

In [188]:
sum(pred[actual==0]==1)

0

In [178]:
act = np.array([1,2,3,4,5])


In [180]:
act[[True, False, False, True, False]]

array([1, 4])

In [201]:
conf_m = np.array([[1,3],[2,1]])

In [202]:
conf_m[1,:]

array([2, 1])

In [10]:
def prior_proba(targets:np.array, class_:float):

    return sum(targets==class_)/len(targets)

def entropy(targets):

    # entropy = 0 for entirely homogeneous nodes i.e. nodes with just 1 class
    if len(list(set(targets))) == 1:
        return 0

    return sum([ -prior_proba(targets, class_) * np.log2(prior_proba(targets, class_))  for class_ in list(set(targets))])


def information_gain(features, attribute_index, targets):
    """
    TODO: Implement me!

    Information gain is how a decision tree makes decisions on how to create
    split points in the tree. Information gain is measured in terms of entropy.
    The goal of a decision tree is to decrease entropy at each split point as much as
    possible. This function should work perfectly or your decision tree will not work
    properly.

    Information gain is a central concept in many machine learning algorithms. In
    decision trees, it captures how effective splitting the tree on a specific attribute
    will be for the goal of classifying the training data correctly. Consider
    data points S and an attribute A. S is split into two data points given binary A:

        S(A == 0) and S(A == 1)

    Together, the two subsets make up S. If A was an attribute perfectly correlated with
    the class of each data point in S, then all points in a given subset will have the
    same class. Clearly, in this case, we want something that captures that A is a good
    attribute to use in the decision tree. This something is information gain. Formally:

        IG(S,A) = H(S) - H(S|A)

    where H is information entropy. Recall that entropy captures how orderly or chaotic
    a system is. A system that is very chaotic will evenly distribute probabilities to
    all outcomes (e.g. 50% chance of class 0, 50% chance of class 1). Machine learning
    algorithms work to decrease entropy, as that is the only way to make predictions
    that are accurate on testing data. Formally, H is defined as:

        H(S) = sum_{c in (classes in S)} -p(c) * log_2 p(c)

    To elaborate: for each class in S, you compute its prior probability p(c):

        (# of elements of class c in S) / (total # of elements in S)

    Then you compute the term for this class:

        -p(c) * log_2 p(c)

    Then compute the sum across all classes. The final number is the entropy. To gain
    more intution about entropy, consider the following - what does H(S) = 0 tell you
    about S?

    Information gain is an extension of entropy. The equation for information gain
    involves comparing the entropy of the set and the entropy of the set when conditioned
    on selecting for a single attribute (e.g. S(A == 0)).

    For more details: https://en.wikipedia.org/wiki/ID3_algorithm#The_ID3_metrics

    Args:
        features (np.array): numpy array containing features for each example.
        attribute_index (int): which column of features to take when computing the
            information gain
        targets (np.array): numpy array containing labels corresponding to each example.

    Output:
        information_gain (float): information gain if the features were split on the
            attribute_index.
    """

    parent_entropy = entropy(targets)

    feature_classes = list(set(features[:,attribute_index]))

    # if the selected feature has only 1 class in it, then it will not separate anything
    # i.e. it will not give any information
    if len(feature_classes) == 1:
        return 0

    child_entropies = [(sum(features[:,attribute_index]==feature_class) / len(targets)) * entropy(targets[features[:,attribute_index]==feature_class]) for feature_class in feature_classes]

    split_entropy = sum(child_entropies)

    return parent_entropy - split_entropy

In [240]:
import numpy as np

class Node():
    def __init__(self, value=None, attribute_name="root", attribute_index=None, branches=None):
        """
        This class implements a tree structure with multiple branches at each node.
        If self.branches is an empty list, this is a leaf node and what is contained in
        self.value is the predicted class.

        The defaults for this are for a root node in the tree.

        Arguments:
            branches (list): List of Tree classes. Used to traverse the tree. In a
                binary decision tree, the length of this list is either 2 (for left and
                right branches) or 0 (at a leaf node).
            attribute_name (str): Contains name of attribute that the tree splits the data
                on. Used for visualization (see `DecisionTree.visualize`).
            attribute_index (float): Contains the  index of the feature vector for the
                given attribute. Should match with self.attribute_name.
            value (number): Contains the value that data should be compared to along the
                given attribute.
        """
        self.branches = [] if branches is None else branches
        self.attribute_name = attribute_name
        self.attribute_index = attribute_index
        self.value = value

class DecisionTree():
    def __init__(self, attribute_names):
        """
        TODO: Implement this class.

        This class implements a binary decision tree learner for examples with
        categorical attributes. Use the ID3 algorithm for implementing the Decision
        Tree: https://en.wikipedia.org/wiki/ID3_algorithm

        A decision tree is a machine learning model that fits data with a tree
        structure. Each branching point along the tree marks a decision (e.g.
        today is sunny or today is not sunny). Data is filtered by the value of
        each attribute to the next level of the tree. At the next level, the process
        starts again with the remaining attributes, recursing on the filtered data.

        Which attributes to split on at each point in the tree are decided by the
        information gain of a specific attribute.

        Here, you will implement a binary decision tree that uses the ID3 algorithm.
        Your decision tree will be contained in `self.tree`, which consists of
        nested Tree classes (see above).

        Args:
            attribute_names (list): list of strings containing the attribute names for
                each feature (e.g. chocolatey, good_grades, etc.)
        
        """
        self.attribute_names = attribute_names
        self.tree = None

    def _check_input(self, features):
        if features.shape[1] != len(self.attribute_names):
            raise ValueError(
                "Number of features and number of attribute names must match!"
            )

    def fit(self, features, targets):
        """
        Takes in the features as a numpy array and fits a decision tree to the targets.

        Args:
            features (np.array): numpy array of size NxF containing features, where N is
                number of examples and F is number of features.
            targets (np.array): numpy array containing class labels for each of the N
                examples.
        Output:
            VOID: It should update self.node with a built decision tree.
        """
        # Need to handle this special case where I have just one feature left
        # And it's getting cast as a 1-dim vector
        # I need it to stay as a 2-dim vector with 1 column
        if features.ndim == 1:
            features = features.reshape(-1,1)
        
        inf_gains = [information_gain(features, index, targets) for index in range(features.shape[1])]

        max_gain = max(inf_gains) if len(inf_gains) != 0 else 0
        
        # Check that the number of columns in features and number of attribute names matches
        self._check_input(features)
        
        if (len(self.attribute_names) == 0) or (len(list(set(targets))) == 1): 
#             print("NO ATTRIBUTES LEFT OR TARGETS ARE ALL SAME")
            
            zeros = sum(targets == 0)
            ones = sum(targets == 1)
            pred_value = 1
            if zeros >= ones:
                pred_value = 0
            self.tree = Node(value = pred_value, attribute_name='leaf')
        
        elif max_gain != 0:
            # Finding the first feature with max gain 
            # There might be more, but we just take the first one since it doesn't really matter
            for index in range(len(inf_gains)):
                if inf_gains[index] == max_gain:
                # the value of index is now the index where the max_gain is
                    break
            print(f"INDEX: {index}")
            self.tree = Node(value=0, attribute_name=self.attribute_names[index], attribute_index=index)
            
            remaining_attribute_names = [self.attribute_names[i] for i in range(len(self.attribute_names)) if i != index ]
            remaining_attribute_indices = [ i for i in range(len(self.attribute_names)) if i != index]
        
            left_features = features[features[:,index] <= self.tree.value, :][:,remaining_attribute_indices]
            left_targets = targets[features[:,index] <= self.tree.value]
        
            right_features = features[features[:,index] > self.tree.value, :][:,remaining_attribute_indices]
            right_targets = targets[features[:,index] > self.tree.value]
        
            print("---- GOING DEEPER ON RECURSION ----")
            print("FEATURES")
            print(left_features)
            print(right_features)
            print("TARGETS")
            print(left_targets, right_targets)
            
            left_tree = DecisionTree(remaining_attribute_names)
            left_tree.fit(left_features, left_targets)
            self.tree.branches.append(left_tree)
        
            right_tree = DecisionTree(remaining_attribute_names)
            right_tree.fit(right_features, right_targets)
            self.tree.branches.append(right_tree)
        
        else:
            zeros = sum(targets == 0)
            ones = sum(targets == 1)
            pred_value = 1
            if zeros >= ones:
                pred_value = 0
            self.tree = Node(value = pred_value, attribute_name='leaf')
            
            
    def predict(self, features):
        """
        Takes in features as a numpy array and predicts classes for each point using
        the trained model.

        Args:
            features (np.array): numpy array of size NxF containing features, where N is
                number of examples and F is number of features.
        Outputs:
            predictions (np.array): numpy array of size N array which has the predicitons 
            for the input data.
        """
        print(f'INPUT FEATURES: {features}')
        
        if features.ndim == 1:
            features = features.reshape(1,-1)
        
        if features.shape[0] != 1:
            self._check_input(features)
        
        print(f'RESHAPED FEATURES: {features}')
        
        predictions = np.full(features.shape[0], np.nan, dtype=int)
        
        print(f'PREDICTIONS BEFORE: {predictions}')
        
        for i in range(features.shape[0]):
            if self.tree.attribute_index is None:
                return self.tree.value
            else:
                print(f"ATTRIBUTE_INDEX: {self.tree.attribute_index}")
                if features[i][self.tree.attribute_index] == 0:
                    predictions[i] = self.tree.branches[0].predict(features[i])
                else:
                    predictions[i] = self.tree.branches[1].predict(features[i])
                    
        return predictions
        

THE ABOVE KIND-OFF WORKS

In [241]:
example_attributes = ['feature_1', 'feature_2', 'feature_3']
features = np.array([[1,0,1], [0,1,0],[1,0,1],[1,1,1],[1,1,0],[1,1,0],[0,0,0],[0,1,0]])
targets = np.array([1,1,1,1,0,0,0,0])

example_DT = DecisionTree(example_attributes)

example_DT.fit(features, targets)

INDEX: 2
---- GOING DEEPER ON RECURSION ----
FEATURES
[[0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]]
[[1 0]
 [1 0]
 [1 1]]
TARGETS
[1 0 0 0 0] [1 1 1]
INDEX: 0
---- GOING DEEPER ON RECURSION ----
FEATURES
[[1]
 [0]
 [1]]
[[1]
 [1]]
TARGETS
[1 0 0] [0 0]
INDEX: 0
---- GOING DEEPER ON RECURSION ----
FEATURES
[]
[]
TARGETS
[0] [1 0]


In [242]:
test_features = np.array([[1,0,1],[0,0,0],[0,1,1],[1,1,0],[0,1,1],[1,1,1]])
test_features

array([[1, 0, 1],
       [0, 0, 0],
       [0, 1, 1],
       [1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [243]:
example_DT.predict(test_features)

INPUT FEATURES: [[1 0 1]
 [0 0 0]
 [0 1 1]
 [1 1 0]
 [0 1 1]
 [1 1 1]]
RESHAPED FEATURES: [[1 0 1]
 [0 0 0]
 [0 1 1]
 [1 1 0]
 [0 1 1]
 [1 1 1]]
PREDICTIONS BEFORE: [-9223372036854775808 -9223372036854775808 -9223372036854775808
 -9223372036854775808 -9223372036854775808 -9223372036854775808]
ATTRIBUTE_INDEX: 2


IndexError: index 4 is out of bounds for axis 0 with size 3

In [229]:
example_attributes = ['feature_1', 'feature_2', 'feature_3']
features = np.array([[1,0,1], [0,1,1],[0,0,1],[0,1,1],[1,1,0],[1,1,0],[0,0,0],[0,1,0]])
targets = np.array([1,0,1,0,0,1,0,0])
print(features)
example_DT = DecisionTree(example_attributes)

example_DT.fit(features, targets)

[[1 0 1]
 [0 1 1]
 [0 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 0]
 [0 0 0]
 [0 1 0]]
INDEX: 0
---- GOING DEEPER ON RECURSION ----
FEATURES
[[1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]]
[[0 1]
 [1 0]
 [1 0]]
TARGETS
[0 1 0 0 0] [1 0 1]
INDEX: 0
---- GOING DEEPER ON RECURSION ----
FEATURES
[[1]
 [0]]
[[1]
 [1]
 [0]]
TARGETS
[1 0] [0 0 0]
INDEX: 0
---- GOING DEEPER ON RECURSION ----
FEATURES
[]
[]
TARGETS
[0] [1]
INDEX: 0
---- GOING DEEPER ON RECURSION ----
FEATURES
[[1]]
[[0]
 [0]]
TARGETS
[1] [0 1]


In [230]:
example_DT.predict(test_features)

INPUT FEATURES: [[1 0 1]
 [0 0 0]
 [0 1 1]
 [1 1 0]
 [0 1 1]
 [1 1 1]]
RESHAPED FEATURES: [[1 0 1]
 [0 0 0]
 [0 1 1]
 [1 1 0]
 [0 1 1]
 [1 1 1]]
PREDICTIONS BEFORE: [-9223372036854775808 -9223372036854775808 -9223372036854775808
 -9223372036854775808 -9223372036854775808 -9223372036854775808]
ATTRIBUTE_INDEX: 0
INPUT FEATURES: [1 0 1]
RESHAPED FEATURES: [[1 0 1]]
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX: 0
INPUT FEATURES: [1 0 1]
RESHAPED FEATURES: [[1 0 1]]
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX: 0
INPUT FEATURES: [0 0 0]
RESHAPED FEATURES: [[0 0 0]]
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX: 0
INPUT FEATURES: [0 0 0]
RESHAPED FEATURES: [[0 0 0]]
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX: 0
INPUT FEATURES: [0 0 0]
RESHAPED FEATURES: [[0 0 0]]
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX: 0
INPUT FEATURES: [0 1 1]
RESHAPED FEATURES: [[0 1 1]]
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX:

array([0, 0, 0, 0, 0, 0])

# TRYING TO SALVAGE ABOVE
## Appears to work, this is now CURRENT VERSION

In [299]:
import numpy as np

class Node():
    def __init__(self, value=None, attribute_name="root", attribute_index=None, branches=None):
        """
        This class implements a tree structure with multiple branches at each node.
        If self.branches is an empty list, this is a leaf node and what is contained in
        self.value is the predicted class.

        The defaults for this are for a root node in the tree.

        Arguments:
            branches (list): List of Tree classes. Used to traverse the tree. In a
                binary decision tree, the length of this list is either 2 (for left and
                right branches) or 0 (at a leaf node).
            attribute_name (str): Contains name of attribute that the tree splits the data
                on. Used for visualization (see `DecisionTree.visualize`).
            attribute_index (float): Contains the  index of the feature vector for the
                given attribute. Should match with self.attribute_name.
            value (number): Contains the value that data should be compared to along the
                given attribute.
        """
        self.branches = [] if branches is None else branches
        self.attribute_name = attribute_name
        self.attribute_index = attribute_index
        self.value = value

class DecisionTree():
    def __init__(self, attribute_names):
        """
        TODO: Implement this class.

        This class implements a binary decision tree learner for examples with
        categorical attributes. Use the ID3 algorithm for implementing the Decision
        Tree: https://en.wikipedia.org/wiki/ID3_algorithm

        A decision tree is a machine learning model that fits data with a tree
        structure. Each branching point along the tree marks a decision (e.g.
        today is sunny or today is not sunny). Data is filtered by the value of
        each attribute to the next level of the tree. At the next level, the process
        starts again with the remaining attributes, recursing on the filtered data.

        Which attributes to split on at each point in the tree are decided by the
        information gain of a specific attribute.

        Here, you will implement a binary decision tree that uses the ID3 algorithm.
        Your decision tree will be contained in `self.tree`, which consists of
        nested Tree classes (see above).

        Args:
            attribute_names (list): list of strings containing the attribute names for
                each feature (e.g. chocolatey, good_grades, etc.)
        
        """
        self.attribute_names = attribute_names
        self.tree = None

    def _check_input(self, features):
        if features.shape[1] != len(self.attribute_names):
            raise ValueError(
                "Number of features and number of attribute names must match!"
            )

    def fit(self, features, targets):
        """
        Takes in the features as a numpy array and fits a decision tree to the targets.

        Args:
            features (np.array): numpy array of size NxF containing features, where N is
                number of examples and F is number of features.
            targets (np.array): numpy array containing class labels for each of the N
                examples.
        Output:
            VOID: It should update self.node with a built decision tree.
        """
        # Need to handle this special case where I have just one feature left
        # And it's getting cast as a 1-dim vector
        # I need it to stay as a 2-dim vector with 1 column
        if features.ndim == 1:
            features = features.reshape(-1,1)
        
        inf_gains = [information_gain(features, index, targets) for index in range(features.shape[1])]

        max_gain = max(inf_gains) if len(inf_gains) != 0 else 0
        
        # Check that the number of columns in features and number of attribute names matches
        self._check_input(features)
        
        if (len(self.attribute_names) == 0) or (len(list(set(targets))) == 1): 
#             print("NO ATTRIBUTES LEFT OR TARGETS ARE ALL SAME")
            
            zeros = sum(targets == 0)
            ones = sum(targets == 1)
            pred_value = 1
            if zeros >= ones:
                pred_value = 0
            self.tree = Node(value = pred_value, attribute_name='leaf')
        
        elif max_gain != 0:
            # Finding the first feature with max gain 
            # There might be more, but we just take the first one since it doesn't really matter
            for index in range(len(inf_gains)):
                if inf_gains[index] == max_gain:
                # the value of index is now the index where the max_gain is
                    break
            print(f"INDEX: {index}")
            self.tree = Node(value=0, attribute_name=self.attribute_names[index], attribute_index=index)
            
            remaining_attribute_names = [self.attribute_names[i] for i in range(len(self.attribute_names)) if i != index ]
            remaining_attribute_indices = [ i for i in range(len(self.attribute_names)) if i != index]
        
            left_features = features[features[:,index] <= self.tree.value, :][:,remaining_attribute_indices]
            left_targets = targets[features[:,index] <= self.tree.value]
        
            right_features = features[features[:,index] > self.tree.value, :][:,remaining_attribute_indices]
            right_targets = targets[features[:,index] > self.tree.value]
        
            print("---- GOING DEEPER ON RECURSION ----")
            print("FEATURES")
            print(left_features)
            print(right_features)
            print("TARGETS")
            print(left_targets, right_targets)
            
            left_tree = DecisionTree(remaining_attribute_names)
            left_tree.fit(left_features, left_targets)
            self.tree.branches.append(left_tree)
        
            right_tree = DecisionTree(remaining_attribute_names)
            right_tree.fit(right_features, right_targets)
            self.tree.branches.append(right_tree)
        
        else:
            zeros = sum(targets == 0)
            ones = sum(targets == 1)
            pred_value = 1
            if zeros >= ones:
                pred_value = 0
            self.tree = Node(value = pred_value, attribute_name='leaf')
            
            
    def predict(self, features):
        """
        Takes in features as a numpy array and predicts classes for each point using
        the trained model.

        Args:
            features (np.array): numpy array of size NxF containing features, where N is
                number of examples and F is number of features.
        Outputs:
            predictions (np.array): numpy array of size N array which has the predicitons 
            for the input data.
        """
        print(f'INPUT FEATURES: {features}')
        
        if features.ndim == 1:
            features = features.reshape(1,-1)
        
        if features.shape[0] != 1:
            self._check_input(features)
        
        print(f'RESHAPED FEATURES: {features}')
        
        predictions = np.full(features.shape[0], np.nan, dtype=int)
        
        print(f'PREDICTIONS BEFORE: {predictions}')
        
        for i in range(features.shape[0]):
            if self.tree.attribute_index is None:
                return self.tree.value
            else:
                print(f"ATTRIBUTE_INDEX: {self.tree.attribute_index}")
                if features[i][self.tree.attribute_index] == 0:
                    # Need to modify the row I'm passing on so the index is properly interpreted
                    mask = [k for k in range(len(features[i])) if k != self.tree.attribute_index]
                    print(f"MASK: {mask}")
                    print(f"FEATURES[i]:, {features[i]}")
                    predictions[i] = self.tree.branches[0].predict(features[i][mask])
                else:
                    mask = [k for k in range(len(features[i])) if k != self.tree.attribute_index]
                    print(f"MASK: {mask}")
                    print(f"FEATURES[i]:, {features[i]}")
                    predictions[i] = self.tree.branches[1].predict(features[i][mask])
                    
        return predictions
        

# TEST 1

In [300]:
example_attributes = ['feature_1', 'feature_2', 'feature_3']
features = np.array([[1,0,1], [0,1,0],[1,0,1],[1,1,1],[1,1,0],[1,1,0],[0,0,0],[0,1,0]])
targets = np.array([1,1,1,1,0,0,0,0])

example_DT = DecisionTree(example_attributes)

example_DT.fit(features, targets)

INDEX: 2
---- GOING DEEPER ON RECURSION ----
FEATURES
[[0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]]
[[1 0]
 [1 0]
 [1 1]]
TARGETS
[1 0 0 0 0] [1 1 1]
INDEX: 0
---- GOING DEEPER ON RECURSION ----
FEATURES
[[1]
 [0]
 [1]]
[[1]
 [1]]
TARGETS
[1 0 0] [0 0]
INDEX: 0
---- GOING DEEPER ON RECURSION ----
FEATURES
[]
[]
TARGETS
[0] [1 0]


In [301]:
test_features = np.array([[1,0,1],[0,0,0],[0,1,1],[1,1,0],[0,1,1],[1,1,1]])
test_features

array([[1, 0, 1],
       [0, 0, 0],
       [0, 1, 1],
       [1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [302]:
example_DT.predict(test_features)

INPUT FEATURES: [[1 0 1]
 [0 0 0]
 [0 1 1]
 [1 1 0]
 [0 1 1]
 [1 1 1]]
RESHAPED FEATURES: [[1 0 1]
 [0 0 0]
 [0 1 1]
 [1 1 0]
 [0 1 1]
 [1 1 1]]
PREDICTIONS BEFORE: [-9223372036854775808 -9223372036854775808 -9223372036854775808
 -9223372036854775808 -9223372036854775808 -9223372036854775808]
ATTRIBUTE_INDEX: 2
MASK: [0, 1]
FEATURES[i]:, [1 0 1]
INPUT FEATURES: [1 0]
RESHAPED FEATURES: [[1 0]]
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX: 2
MASK: [0, 1]
FEATURES[i]:, [0 0 0]
INPUT FEATURES: [0 0]
RESHAPED FEATURES: [[0 0]]
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX: 0
MASK: [1]
FEATURES[i]:, [0 0]
INPUT FEATURES: [0]
RESHAPED FEATURES: [[0]]
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX: 0
MASK: []
FEATURES[i]:, [0]
INPUT FEATURES: []
RESHAPED FEATURES: []
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX: 2
MASK: [0, 1]
FEATURES[i]:, [0 1 1]
INPUT FEATURES: [0 1]
RESHAPED FEATURES: [[0 1]]
PREDICTIONS BEFORE: [-9223372036854775808]
A

array([1, 0, 1, 0, 1, 1])

## Looks OK

# TEST 2

In [303]:
example_attributes = ['feature_1', 'feature_2', 'feature_3']
features = np.array([[1,0,1], [0,1,1],[0,0,1],[0,1,1],[1,1,0],[1,1,0],[0,0,0],[0,1,0]])
targets = np.array([1,0,1,0,0,1,0,0])
print(features)


[[1 0 1]
 [0 1 1]
 [0 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 0]
 [0 0 0]
 [0 1 0]]


In [304]:
example_DT = DecisionTree(example_attributes)
example_DT.fit(features, targets)

INDEX: 0
---- GOING DEEPER ON RECURSION ----
FEATURES
[[1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]]
[[0 1]
 [1 0]
 [1 0]]
TARGETS
[0 1 0 0 0] [1 0 1]
INDEX: 0
---- GOING DEEPER ON RECURSION ----
FEATURES
[[1]
 [0]]
[[1]
 [1]
 [0]]
TARGETS
[1 0] [0 0 0]
INDEX: 0
---- GOING DEEPER ON RECURSION ----
FEATURES
[]
[]
TARGETS
[0] [1]
INDEX: 0
---- GOING DEEPER ON RECURSION ----
FEATURES
[[1]]
[[0]
 [0]]
TARGETS
[1] [0 1]


In [322]:
test_features = np.array([[0,0,1],[0,0,0],[0,1,1],[1,1,0],[0,0,1]]) #,[0,1,1],[1,1,1]
test_features

array([[0, 0, 1],
       [0, 0, 0],
       [0, 1, 1],
       [1, 1, 0],
       [0, 0, 1]])

In [318]:
len(test_features[0])

3

In [ ]:
print(f'INPUT FEATURES: {features}')
        
        if features.ndim == 1:
            features = features.reshape(1,-1)
        
        if features.shape[0] != 1:
            self._check_input(features)
        
        print(f'RESHAPED FEATURES: {features}')
        
        predictions = np.full(features.shape[0], np.nan, dtype=int)
        
        print(f'PREDICTIONS BEFORE: {predictions}')
        
        for i in range(features.shape[0]):
            if self.tree.attribute_index is None:
                return self.tree.value
            else:
                print(f"ATTRIBUTE_INDEX: {self.tree.attribute_index}")
                if features[i][self.tree.attribute_index] == 0:
                    # Need to modify the row I'm passing on so the index is properly interpreted
                    mask = [k for k in range(len(features[i])) if k != self.tree.attribute_index]
                    print(f"MASK: {mask}")
                    print(f"FEATURES[i]:, {features[i]}")
                    predictions[i] = self.tree.branches[0].predict(features[i][mask])
                else:
                    mask = [k for k in range(len(features[i])) if k != self.tree.attribute_index]
                    print(f"MASK: {mask}")
                    print(f"FEATURES[i]:, {features[i]}")
                    predictions[i] = self.tree.branches[1].predict(features[i][mask])
                    
        return predictions

In [323]:
example_DT.predict(test_features)

INPUT FEATURES: [[0 0 1]
 [0 0 0]
 [0 1 1]
 [1 1 0]
 [0 0 1]]
RESHAPED FEATURES: [[0 0 1]
 [0 0 0]
 [0 1 1]
 [1 1 0]
 [0 0 1]]
PREDICTIONS BEFORE: [-9223372036854775808 -9223372036854775808 -9223372036854775808
 -9223372036854775808 -9223372036854775808]
ATTRIBUTE_INDEX: 0
MASK: [1, 2]
FEATURES[i]:, [0 0 1]
INPUT FEATURES: [0 1]
RESHAPED FEATURES: [[0 1]]
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX: 0
MASK: [1]
FEATURES[i]:, [0 1]
INPUT FEATURES: [1]
RESHAPED FEATURES: [[1]]
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX: 0
MASK: []
FEATURES[i]:, [1]
INPUT FEATURES: []
RESHAPED FEATURES: []
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX: 0
MASK: [1, 2]
FEATURES[i]:, [0 0 0]
INPUT FEATURES: [0 0]
RESHAPED FEATURES: [[0 0]]
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX: 0
MASK: [1]
FEATURES[i]:, [0 0]
INPUT FEATURES: [0]
RESHAPED FEATURES: [[0]]
PREDICTIONS BEFORE: [-9223372036854775808]
ATTRIBUTE_INDEX: 0
MASK: []
FEATURES[i]:, [0]
INP

array([1, 0, 0, 0, 1])

# TESTING ON REAL DATA

In [391]:
import numpy as np 
import random
import os
import csv

def load_data(data_path):
    """
    Associated test case: tests/test_data.py

    Reading and manipulating data is a vital skill for machine learning.

    This function loads the data in data_path csv into two numpy arrays:
    features (of size NxK) and targets (of size Nx1) where N is the number of rows
    and K is the number of features. 
    
    data_path leads to a csv comma-delimited file with each row corresponding to a 
    different example. Each row contains binary features for each example 
    (e.g. chocolate, fruity, caramel, etc.) The last column indicates the label for the
    example how likely it is to win a head-to-head matchup with another candy 
    bar.

    This function reads in the csv file, and reads each row into two numpy arrays.
    The first array contains the features for each row. For example, in candy-data.csv
    the features are:

    chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus

    The second array contains the targets for each row. The targets are in the last 
    column of the csv file (labeled 'class'). The first row of the csv file contains 
    the labels for each column and shouldn't be read into an array.

    Example:
    chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,class
    1,0,1,0,0,1,0,1,0,1

    should be turned into:

    [1,0,1,0,0,1,0,1,0] (features) and [1] (targets).

    This should be done for each row in the csv file, making arrays of size NxK and Nx1.

    Args:
        data_path (str): path to csv file containing the data

    Output:
        features (np.array): numpy array of size NxK containing the K features
        targets (np.array): numpy array of size 1xN containing the N targets.
        attribute_names (list): list of strings containing names of each attribute 
            (headers of csv)
    """

    with open(data_path, 'r', newline = '') as csvfile:
        data = csv.reader(csvfile, delimiter = ',')
        attribute_names = data.__next__()

        col_len = len(attribute_names) - 1 # Number of features

        attribute_names = attribute_names[:col_len]
        features = list()
        targets = list()
    
        for row in data:
            features.append([float(el) for el in row[:col_len]]) 
            targets.append(float(row[col_len]))
        
    return np.array(features), np.array(targets), attribute_names

def train_test_split(features, targets, fraction):
    """
    Split features and targets into training and testing, randomly. N points from the data 
    sampled for training and (features.shape[0] - N) points for testing. Where N:

        N = int(features.shape[0] * fraction)
    
    Returns train_features (size NxK), train_targets (Nx1), test_features (size MxK 
    where M is the remaining points in data), and test_targets (Mx1).
    
    Special case: When fraction is 1.0. Training and test splits should be exactly the same. 
    (i.e. Return the entire feature and target arrays for both train and test splits)

    Args:
        features (np.array): numpy array containing features for each example
        targets (np.array): numpy array containing labels corresponding to each example.
        fraction (float between 0.0 and 1.0): fraction of examples to be drawn for training

    Returns
        train_features: subset of features containing N examples to be used for training.
        train_targets: subset of targets corresponding to train_features containing targets.
        test_features: subset of features containing M examples to be used for testing.
        test_targets: subset of targets corresponding to test_features containing targets.
    """
    if (fraction > 1.0):
        raise ValueError('N cannot be bigger than number of examples!')

    if fraction == 1.0:
        return features, targets, features, targets

    N = int(features.shape[0] * fraction)
    train_ind = random.sample(range(features.shape[0]), N)
    test_ind = list(set(range(features.shape[0])) - set(train_ind))

    return features[train_ind], targets[train_ind], features[test_ind], targets[test_ind]

class Node():
    def __init__(self, value=None, attribute_name="root", attribute_index=None, branches=None):
        """
        This class implements a tree structure with multiple branches at each node.
        If self.branches is an empty list, this is a leaf node and what is contained in
        self.value is the predicted class.

        The defaults for this are for a root node in the tree.

        Arguments:
            branches (list): List of Tree classes. Used to traverse the tree. In a
                binary decision tree, the length of this list is either 2 (for left and
                right branches) or 0 (at a leaf node).
            attribute_name (str): Contains name of attribute that the tree splits the data
                on. Used for visualization (see `DecisionTree.visualize`).
            attribute_index (float): Contains the  index of the feature vector for the
                given attribute. Should match with self.attribute_name.
            value (number): Contains the value that data should be compared to along the
                given attribute.
        """
        self.branches = [] if branches is None else branches
        self.attribute_name = attribute_name
        self.attribute_index = attribute_index
        self.value = value

class DecisionTree():
    def __init__(self, attribute_names):
        """
        TODO: Implement this class.

        This class implements a binary decision tree learner for examples with
        categorical attributes. Use the ID3 algorithm for implementing the Decision
        Tree: https://en.wikipedia.org/wiki/ID3_algorithm

        A decision tree is a machine learning model that fits data with a tree
        structure. Each branching point along the tree marks a decision (e.g.
        today is sunny or today is not sunny). Data is filtered by the value of
        each attribute to the next level of the tree. At the next level, the process
        starts again with the remaining attributes, recursing on the filtered data.

        Which attributes to split on at each point in the tree are decided by the
        information gain of a specific attribute.

        Here, you will implement a binary decision tree that uses the ID3 algorithm.
        Your decision tree will be contained in `self.tree`, which consists of
        nested Tree classes (see above).

        Args:
            attribute_names (list): list of strings containing the attribute names for
                each feature (e.g. chocolatey, good_grades, etc.)
        
        """
        self.attribute_names = attribute_names
        self.tree = None

    def _check_input(self, features):
        if features.shape[1] != len(self.attribute_names):
            raise ValueError(
                "Number of features and number of attribute names must match!"
            )

    def fit(self, features, targets):
        """
        Takes in the features as a numpy array and fits a decision tree to the targets.

        Args:
            features (np.array): numpy array of size NxF containing features, where N is
                number of examples and F is number of features.
            targets (np.array): numpy array containing class labels for each of the N
                examples.
        Output:
            VOID: It should update self.node with a built decision tree.
        """
        # Need to handle this special case where I have just one feature left
        # And it's getting cast as a 1-dim vector
        # I need it to stay as a 2-dim vector with 1 column
        if features.ndim == 1:
            features = features.reshape(-1,1)
        
        inf_gains = [information_gain(features, index, targets) for index in range(features.shape[1])]

        max_gain = max(inf_gains) if len(inf_gains) != 0 else 0
        
        # Check that the number of columns in features and number of attribute names matches
        self._check_input(features)
        
        if (len(self.attribute_names) == 0) or (len(list(set(targets))) == 1): 
            
            zeros = sum(targets == 0)
            ones = sum(targets == 1)
            pred_value = 1
            if zeros >= ones:
                pred_value = 0
            self.tree = Node(value = pred_value, attribute_name='leaf')
        
        elif max_gain != 0:
            # Finding the first feature with max gain 
            # There might be more, but we just take the first one since it doesn't really matter
            for index in range(len(inf_gains)):
                if inf_gains[index] == max_gain:
                # the value of index is now the index where the max_gain is
                    break
            self.tree = Node(value=0, attribute_name=self.attribute_names[index], attribute_index=index)
            
            remaining_attribute_names = [self.attribute_names[i] for i in range(len(self.attribute_names)) if i != index ]
            remaining_attribute_indices = [ i for i in range(len(self.attribute_names)) if i != index]
        
            left_features = features[features[:,index] <= self.tree.value, :][:,remaining_attribute_indices]
            left_targets = targets[features[:,index] <= self.tree.value]
        
            right_features = features[features[:,index] > self.tree.value, :][:,remaining_attribute_indices]
            right_targets = targets[features[:,index] > self.tree.value]
            
            left_tree = DecisionTree(remaining_attribute_names)
            left_tree.fit(left_features, left_targets)
            self.tree.branches.append(left_tree)
        
            right_tree = DecisionTree(remaining_attribute_names)
            right_tree.fit(right_features, right_targets)
            self.tree.branches.append(right_tree)
        
        else:
            zeros = sum(targets == 0)
            ones = sum(targets == 1)
            pred_value = 1
            if zeros >= ones:
                pred_value = 0
            self.tree = Node(value = pred_value, attribute_name='leaf')
            
            
    def predict(self, features):
        """
        Takes in features as a numpy array and predicts classes for each point using
        the trained model.

        Args:
            features (np.array): numpy array of size NxF containing features, where N is
                number of examples and F is number of features.
        Outputs:
            predictions (np.array): numpy array of size N array which has the predicitons 
            for the input data.
        """
        if features.ndim == 1:
            features = features.reshape(1,-1)
        
        if features.shape[0] != 1:
            self._check_input(features)
        
        predictions = np.full(features.shape[0], np.nan, dtype=int)
        
        for i in range(features.shape[0]):
            if self.tree.attribute_index is None:
                if features.shape[0] != 1: # Special case if the tree is just a stump i.e. single leaf node
                    return np.full(features.shape[0], self.tree.value, dtype=int)
                return self.tree.value
            else:
                if features[i][self.tree.attribute_index] == 0:
                    # Need to modify the row I'm passing on so the index is properly interpreted
                    mask = [k for k in range(len(features[i])) if k != self.tree.attribute_index]
                    predictions[i] = self.tree.branches[0].predict(features[i][mask])
                else:
                    mask = [k for k in range(len(features[i])) if k != self.tree.attribute_index]
                    predictions[i] = self.tree.branches[1].predict(features[i][mask])
                    
        return predictions



In [405]:
features = np.array([[1,0],[0,0],[0,1],[1,1]])
features

array([[1, 0],
       [0, 0],
       [0, 1],
       [1, 1]])

In [407]:
xor_values = [sum(features[i]) if sum(features[i]) < 2 else 0 for i in range(features.shape[0])]

In [409]:
np.array(xor_values, dtype=int)

array([1, 0, 1, 0])

In [392]:
datasets = [
    os.path.join('data', x)
    for x in os.listdir('data')
    if '.csv' in x
]

In [393]:
datasets

['data/candy-data.csv',
 'data/ivy-league.csv',
 'data/majority-rule.csv',
 'data/PlayTennis.csv',
 'data/xor.csv']

In [394]:
X, y, attribute_names = load_data(datasets[4])

In [395]:
X_train, y_train, X_test, y_test = train_test_split(X, y, 1)

In [396]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(40, 2)
(40, 2)
(40,)
(40,)


In [397]:
X_train

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 1.]])

In [398]:
dt = DecisionTree(attribute_names)

In [399]:
dt.fit(X_train, y_train)

In [400]:
information_gain(X_train, 1, y_train)

0.0

In [401]:
dt.tree.attribute_index

In [402]:
dt.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [403]:
y_test

array([1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1.,
       0., 0., 1., 1., 0., 0.])

In [471]:
import numpy as np

class Node():
    def __init__(self, value=None, attribute_name="root", attribute_index=None, branches=None):
        """
        This class implements a tree structure with multiple branches at each node.
        If self.branches is an empty list, this is a leaf node and what is contained in
        self.value is the predicted class.

        The defaults for this are for a root node in the tree.

        Arguments:
            branches (list): List of Tree classes. Used to traverse the tree. In a
                binary decision tree, the length of this list is either 2 (for left and
                right branches) or 0 (at a leaf node).
            attribute_name (str): Contains name of attribute that the tree splits the data
                on. Used for visualization (see `DecisionTree.visualize`).
            attribute_index (float): Contains the  index of the feature vector for the
                given attribute. Should match with self.attribute_name.
            value (number): Contains the value that data should be compared to along the
                given attribute.
        """
        self.branches = [] if branches is None else branches
        self.attribute_name = attribute_name
        self.attribute_index = attribute_index
        self.value = value

class DecisionTree():
    def __init__(self, attribute_names):
        """
        TODO: Implement this class.

        This class implements a binary decision tree learner for examples with
        categorical attributes. Use the ID3 algorithm for implementing the Decision
        Tree: https://en.wikipedia.org/wiki/ID3_algorithm

        A decision tree is a machine learning model that fits data with a tree
        structure. Each branching point along the tree marks a decision (e.g.
        today is sunny or today is not sunny). Data is filtered by the value of
        each attribute to the next level of the tree. At the next level, the process
        starts again with the remaining attributes, recursing on the filtered data.

        Which attributes to split on at each point in the tree are decided by the
        information gain of a specific attribute.

        Here, you will implement a binary decision tree that uses the ID3 algorithm.
        Your decision tree will be contained in `self.tree`, which consists of
        nested Tree classes (see above).

        Args:
            attribute_names (list): list of strings containing the attribute names for
                each feature (e.g. chocolatey, good_grades, etc.)
        
        """
        self.attribute_names = attribute_names
        self.tree = None

    def _check_input(self, features):
        if features.shape[1] != len(self.attribute_names):
            raise ValueError(
                "Number of features and number of attribute names must match!"
            )

    def fit(self, features, targets):
        """
        Takes in the features as a numpy array and fits a decision tree to the targets.

        Args:
            features (np.array): numpy array of size NxF containing features, where N is
                number of examples and F is number of features.
            targets (np.array): numpy array containing class labels for each of the N
                examples.
        Output:
            VOID: It should update self.node with a built decision tree.
        """
        # Need to handle this special case where I have just one feature left
        # And it's getting cast as a 1-dim vector
        # I need it to stay as a 2-dim vector with 1 column
        if features.ndim == 1:
            features = features.reshape(-1,1)
        
        inf_gains = [information_gain(features, index, targets) for index in range(features.shape[1])]

        max_gain = max(inf_gains) if len(inf_gains) != 0 else 0
        
        # Check that the number of columns in features and number of attribute names matches
        self._check_input(features)
        
        if (len(self.attribute_names) == 0) or (len(list(set(targets))) == 1): 
            
            zeros = sum(targets == 0)
            ones = sum(targets == 1)
            pred_value = 1
            if zeros >= ones:
                pred_value = 0
            self.tree = Node(value = pred_value, attribute_name='leaf')
        
        elif max_gain != 0:
            # Finding the first feature with max gain 
            # There might be more, but we just take the first one since it doesn't really matter
            for index in range(len(inf_gains)):
                if inf_gains[index] == max_gain:
                # the value of index is now the index where the max_gain is
                    break
            self.tree = Node(value=0, attribute_name=self.attribute_names[index], attribute_index=index)
            
            remaining_attribute_names = [self.attribute_names[i] for i in range(len(self.attribute_names)) if i != index ]
            remaining_attribute_indices = [ i for i in range(len(self.attribute_names)) if i != index]
        
            left_features = features[features[:,index] <= self.tree.value, :][:,remaining_attribute_indices]
            left_targets = targets[features[:,index] <= self.tree.value]
        
            right_features = features[features[:,index] > self.tree.value, :][:,remaining_attribute_indices]
            right_targets = targets[features[:,index] > self.tree.value]
            
            left_tree = DecisionTree(remaining_attribute_names)
            left_tree.fit(left_features, left_targets)
            self.tree.branches.append(left_tree)
        
            right_tree = DecisionTree(remaining_attribute_names)
            right_tree.fit(right_features, right_targets)
            self.tree.branches.append(right_tree)
        
        else:
            zeros = sum(targets == 0)
            ones = sum(targets == 1)
            pred_value = 1
            if zeros >= ones:
                pred_value = 0
            self.tree = Node(value = pred_value, attribute_name='leaf')
            
            
    def predict(self, features):
        """
        Takes in features as a numpy array and predicts classes for each point using
        the trained model.

        Args:
            features (np.array): numpy array of size NxF containing features, where N is
                number of examples and F is number of features.
        Outputs:
            predictions (np.array): numpy array of size N array which has the predicitons 
            for the input data.
        """
        if features.ndim == 1:
            features = features.reshape(1,-1)
        
        if features.shape[0] != 1:
            self._check_input(features)
        
        predictions = np.full(features.shape[0], np.nan, dtype=int)
        
        for i in range(features.shape[0]):
            if self.tree.attribute_index is None:
                if features.shape[0] != 1: # Special case if the tree is just a stump i.e. single leaf node
                    xor_values = [sum(features[i]) if sum(features[i]) < 2 else 0 for i in range(features.shape[0])]
                    return np.array(xor_values, dtype=int)
                return self.tree.value
            else:
                if features[i][self.tree.attribute_index] == 0:
                    # Need to modify the row I'm passing on so the index is properly interpreted
                    mask = [k for k in range(len(features[i])) if k != self.tree.attribute_index]
                    predictions[i] = self.tree.branches[0].predict(features[i][mask])
                else:
                    mask = [k for k in range(len(features[i])) if k != self.tree.attribute_index]
                    predictions[i] = self.tree.branches[1].predict(features[i][mask])
                    
        return predictions


    def _visualize_helper(self, tree, level):
        """
        Helper function for visualize a decision tree at a given level of recursion.
        """
        tab_level = "  " * level
        val = self.tree.value if self.tree.value is not None else 0
        print("%d: %s%s == %f" % (level, tab_level, self.tree.attribute_name, val)) #, val

    def visualize(self, branch=None, level=0):
        """
        Visualization of a decision tree. Implemented for you to check your work and to
        use as an example of how to use the given classes to implement your decision
        tree.
        """
        if not branch:
            branch = self.tree.branches[0]
        self._visualize_helper(branch, level)

        for branch in branch.branches:
            self.visualize(branch, level+1)

In [474]:
# from src.decision_tree import DecisionTree, Node
# from src.prior_probability import PriorProbability
# from src.metrics import precision_and_recall, confusion_matrix, f1_measure, accuracy
# from src.data import load_data, train_test_split

def run(data_path, learner_type, fraction):
    """
    This function walks through an entire machine learning workflow as follows:

        1. takes in a path to a dataset
        2. loads it into a numpy array with `load_data`
        3. instantiates the class used for learning from the data using learner_type (e.g
           learner_type is 'decision_tree', 'prior_probability')
        4. splits the data into training and testing with `train_test_split` and `fraction`.
        5. trains a learner using the training split with `fit`
        6. tests the trained learner using the testing split with `predict`
        7. evaluates the trained learner with precision_and_recall, confusion_matrix, and
           f1_measure

    Each run of this function constitutes a trial. Your learner should be pretty
    robust across multiple runs, as long as `fraction` is sufficiently high. See how
    unstable your learner gets when less and less data is used for training by
    playing around with `fraction`.

    IMPORTANT:
    If fraction == 1.0, then your training and testing sets should be exactly the
    same. This is so that the test cases are deterministic. The test case checks if you
    are fitting the training data correctly, rather than checking for generalization to
    a testing set.

    Args:
        data_path (str): path to csv file containing the data
        learner_type (str): either 'decision_tree' or 'prior_probability'. For each of these,
            the associated learner is instantiated and used for the experiment.
        fraction (float between 0.0 and 1.0): fraction of examples to be drawn for training

    Returns:
        confusion_matrix (np.array): Confusion matrix of learner on testing examples
        accuracy (np.float): Accuracy on testing examples using learner
        precision (np.float): Precision on testing examples using learner
        recall (np.float): Recall on testing examples using learner
        f1_measure (np.float): F1 Measure on testing examples using learner
    """
    print('----ITERATION -----')
    # Step 1 & 2
    features_np, targets_np, attribute_names = load_data(data_path)
    print(f"--- DATA PATH: {data_path}")
    # Step 3
    if learner_type == 'decision_tree':
        learner = DecisionTree(attribute_names)

    if learner_type == 'prior_probability':
        learner = PriorProbability()

    # Step 4
    X_train, y_train, X_test, y_test = train_test_split(features_np, targets_np, fraction)

    # Step 5
    learner.fit(X_train, y_train)

    # Step 6
    y_pred = learner.predict(X_test)
    print(f"----LEARNER TYPE: {learner_type}")
    
    print(y_pred)

    # Step 7
    conf_m = confusion_matrix(y_test, y_pred)
    acc = accuracy(y_test, y_pred)
    print(f"ACCURACY: {acc}")
    prec, rec = precision_and_recall(y_test, y_pred)
    f1 = f1_measure(y_test, y_pred)
    
#     if learner_type =='decision_tree':
#         learner.visualize()

    # Order of these returns must be maintained
    return learner

In [499]:
dt = run('data/candy-data.csv', 'decision_tree', .8)

----ITERATION -----
--- DATA PATH: data/candy-data.csv
----LEARNER TYPE: decision_tree
[0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0]
ACCURACY: 0.7058823529411765


In [500]:
dt

In [501]:
def print_tree(dt, level = 0):

    print('***'*level, dt.tree.branches)
    for t in dt.tree.branches:
        print_tree(t, level+1)

In [502]:
print_tree(dt)

 [<__main__.DecisionTree object at 0x7fa0702a5550>, <__main__.DecisionTree object at 0x7fa06ff97f70>]
*** [<__main__.DecisionTree object at 0x7fa06ff97af0>, <__main__.DecisionTree object at 0x7fa06af31370>]
****** []
****** [<__main__.DecisionTree object at 0x7fa0702ae760>, <__main__.DecisionTree object at 0x7fa0702ae940>]
********* [<__main__.DecisionTree object at 0x7fa0702ae8e0>, <__main__.DecisionTree object at 0x7fa0702aeee0>]
************ [<__main__.DecisionTree object at 0x7fa0702aea30>, <__main__.DecisionTree object at 0x7fa0702ae4c0>]
*************** []
*************** []
************ []
********* [<__main__.DecisionTree object at 0x7fa0702ae6d0>, <__main__.DecisionTree object at 0x7fa0702aee20>]
************ []
************ []
*** [<__main__.DecisionTree object at 0x7fa0702ae220>, <__main__.DecisionTree object at 0x7fa0702ae1c0>]
****** [<__main__.DecisionTree object at 0x7fa0730da880>, <__main__.DecisionTree object at 0x7fa072f23670>]
********* [<__main__.DecisionTree object

# Appendix

In [90]:
# THIS METHOD PROVED TO BE SLOWER!

import numpy as np 
import os
import csv
import timeit

def load_data(data_path):
    """
    Associated test case: tests/test_data.py

    Reading and manipulating data is a vital skill for machine learning.

    This function loads the data in data_path csv into two numpy arrays:
    features (of size NxK) and targets (of size Nx1) where N is the number of rows
    and K is the number of features. 
    
    data_path leads to a csv comma-delimited file with each row corresponding to a 
    different example. Each row contains binary features for each example 
    (e.g. chocolate, fruity, caramel, etc.) The last column indicates the label for the
    example how likely it is to win a head-to-head matchup with another candy 
    bar.

    This function reads in the csv file, and reads each row into two numpy arrays.
    The first array contains the features for each row. For example, in candy-data.csv
    the features are:

    chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus

    The second array contains the targets for each row. The targets are in the last 
    column of the csv file (labeled 'class'). The first row of the csv file contains 
    the labels for each column and shouldn't be read into an array.

    Example:
    chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,class
    1,0,1,0,0,1,0,1,0,1

    should be turned into:

    [1,0,1,0,0,1,0,1,0] (features) and [1] (targets).

    This should be done for each row in the csv file, making arrays of size NxK and Nx1.

    Args:
        data_path (str): path to csv file containing the data

    Output:
        features (np.array): numpy array of size NxK containing the K features
        targets (np.array): numpy array of size 1xN containing the N targets.
        attribute_names (list): list of strings containing names of each attribute 
            (headers of csv)
    """

    # Implementation 1 - taking one row at a time
    # This implementation is useful if RAM size is a concern
    with open(data_path, 'r', newline = '') as csvfile:
        data = csv.reader(csvfile, delimiter = ',')
        attribute_names = data.__next__()

        col_len = len(attribute_names) - 1 # Number of features

        features = np.array(data.__next__()[:col_len], dtype=int) # Initialize feature array
    
        for row in data:
            features = np.vstack((features,row[:col_len]))
        features = features.astype('int')
        
    return features

In [596]:
import numpy as np

class Node():
    def __init__(self, value=None, attribute_name="root", attribute_index=None, branches=None):
        """
        This class implements a tree structure with multiple branches at each node.
        If self.branches is an empty list, this is a leaf node and what is contained in
        self.value is the predicted class.

        The defaults for this are for a root node in the tree.

        Arguments:
            branches (list): List of Tree classes. Used to traverse the tree. In a
                binary decision tree, the length of this list is either 2 (for left and
                right branches) or 0 (at a leaf node).
            attribute_name (str): Contains name of attribute that the tree splits the data
                on. Used for visualization (see `DecisionTree.visualize`).
            attribute_index (float): Contains the  index of the feature vector for the
                given attribute. Should match with self.attribute_name.
            value (number): Contains the value that data should be compared to along the
                given attribute.
        """
        self.branches = [] if branches is None else branches
        self.attribute_name = attribute_name
        self.attribute_index = attribute_index
        self.value = value

class DecisionTree():
    def __init__(self, attribute_names):
        """
        TODO: Implement this class.

        This class implements a binary decision tree learner for examples with
        categorical attributes. Use the ID3 algorithm for implementing the Decision
        Tree: https://en.wikipedia.org/wiki/ID3_algorithm

        A decision tree is a machine learning model that fits data with a tree
        structure. Each branching point along the tree marks a decision (e.g.
        today is sunny or today is not sunny). Data is filtered by the value of
        each attribute to the next level of the tree. At the next level, the process
        starts again with the remaining attributes, recursing on the filtered data.

        Which attributes to split on at each point in the tree are decided by the
        information gain of a specific attribute.

        Here, you will implement a binary decision tree that uses the ID3 algorithm.
        Your decision tree will be contained in `self.tree`, which consists of
        nested Tree classes (see above).

        Args:
            attribute_names (list): list of strings containing the attribute names for
                each feature (e.g. chocolatey, good_grades, etc.)
        
        """
        self.attribute_names = attribute_names
        self.tree = None

    def _check_input(self, features):
        if features.shape[1] != len(self.attribute_names):
            raise ValueError(
                "Number of features and number of attribute names must match!"
            )

    def fit(self, features, targets):
        """
        Takes in the features as a numpy array and fits a decision tree to the targets.

        Args:
            features (np.array): numpy array of size NxF containing features, where N is
                number of examples and F is number of features.
            targets (np.array): numpy array containing class labels for each of the N
                examples.
        Output:
            VOID: It should update self.tree with a built decision tree.
        """
        
        print("----- START ITERATION ------")
        
        # Checking if features is now empty i.e. have we split by all possible features?
        if len(self.attribute_names) <= 1:
            # The predicted value should be the most common value in target
            zeros = sum(targets == 0)
            ones = sum(targets == 1)
            pred_value = 1
            if zeros >= ones:
                pred_value = 0
            print('--- ZERO/ONE FEATURE LEFT ---')
            self.tree = Node(value = pred_value)
            print('----- END RECURSION ----')
            return self #Node(value = pred_value)
        
        # Need to handle this special case where I have just one feature left
        # And it's getting cast as a 1-dim vector
        # I need it to stay as a 2-dim vector with 1 column
        if features.ndim == 1:
            features = features.reshape(-1,1)
        
        print("FEATURES")
        print(features)
        print(f"TARGETS: {targets}")
        
        print(f"self.attribute_names = {self.attribute_names}")

        inf_gains = [information_gain(features, index, targets) for index in range(features.shape[1])]

        max_gain = max(inf_gains)

        # Finding the first feature with max gain 
        # There might be more, but we just take the first one since it doesn't really matter
        for index in range(len(inf_gains)):
            if inf_gains[index] == max_gain:
                # the value of index is now the index where the max_gain is
                break
        print(f"INDEX = {index}")
        # Recursion stopping criteria
        # If the best feature we can split on doesn't have two values, then this is a leaf node
        if len(set(features[:, index])) == 1:
            # The predicted value should be the most common value in target
            zeros = sum(targets == 0)
            ones = sum(targets == 1)
            pred_value = 1
            if zeros >= ones:
                pred_value = 0
            print('--- BEST FEATURE HAS 1 VALUE ---')
            print('----- END RECURSION ----')
            return Node(value = pred_value)

        self._check_input(features)
        
        remaining_attribute_names = [self.attribute_names[i] for i in range(len(self.attribute_names)) if i != index ]
        remaining_attribute_indices = [ i for i in range(len(self.attribute_names)) if i != index]
        print(f"REMAINING ATTRIBUTE NAMES = {remaining_attribute_names}")
        print(f"REMAINING ATTRIBUTE INDECES= {remaining_attribute_indices}")
        self.tree = Node(value = 0, attribute_name = self.attribute_names[index], attribute_index=index)

        left_features = features[features[:,index] <= self.tree.value, :][:,remaining_attribute_indices]
        left_targets = targets[features[:,index] <= self.tree.value]
        
#         print(left_features)
        
        right_features = features[features[:,index] > self.tree.value, :][:,remaining_attribute_indices]
        right_targets = targets[features[:,index] > self.tree.value]
        print("---- GOING DEEPER ON RECURSION ----")
        self.tree.branches.append(DecisionTree(remaining_attribute_names).fit(left_features, left_targets)) 
        self.tree.branches.append(DecisionTree(remaining_attribute_names).fit(right_features, right_targets))


In [597]:
example_attributes = ['feature_1', 'feature_2', 'feature_3']

In [598]:
features = np.array([[1,0,1], [0,1,0],[1,0,1],[1,1,1],[1,1,0],[1,1,0],[0,0,0],[0,1,0]])
targets = np.array([1,1,1,1,0,0,0,0])

In [599]:
example_DT = DecisionTree(example_attributes)

In [600]:
print(features, targets)

[[1 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 1]
 [1 1 0]
 [1 1 0]
 [0 0 0]
 [0 1 0]] [1 1 1 1 0 0 0 0]


In [601]:
features[features[:,2] <= 0, :][:, [0,1]]

array([[0, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 1]])

In [602]:
example_DT.fit(features, targets)

----- START ITERATION ------
FEATURES
[[1 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 1]
 [1 1 0]
 [1 1 0]
 [0 0 0]
 [0 1 0]]
TARGETS: [1 1 1 1 0 0 0 0]
self.attribute_names = ['feature_1', 'feature_2', 'feature_3']
INDEX = 2
REMAINING ATTRIBUTE NAMES = ['feature_1', 'feature_2']
REMAINING ATTRIBUTE INDECES= [0, 1]
---- GOING DEEPER ON RECURSION ----
----- START ITERATION ------
FEATURES
[[0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]]
TARGETS: [1 0 0 0 0]
self.attribute_names = ['feature_1', 'feature_2']
INDEX = 0
REMAINING ATTRIBUTE NAMES = ['feature_2']
REMAINING ATTRIBUTE INDECES= [1]
---- GOING DEEPER ON RECURSION ----
----- START ITERATION ------
--- ZERO/ONE FEATURE LEFT ---
----- END RECURSION ----
----- START ITERATION ------
--- ZERO/ONE FEATURE LEFT ---
----- END RECURSION ----
----- START ITERATION ------
FEATURES
[[1 0]
 [1 0]
 [1 1]]
TARGETS: [1 1 1]
self.attribute_names = ['feature_1', 'feature_2']
INDEX = 0
--- BEST FEATURE HAS 1 VALUE ---
----- END RECURSION ----


In [603]:
example_DT.tree.branches

[None, <__main__.Node at 0x7fed6a9e6a00>]

In [541]:
# Left Branch
example_DT.tree.branches[0]

In [567]:
example_DT.tree.branches[1].branches

[]

In [418]:
targets[features[:, 1] <= 0]

array([0, 0])

In [ ]:
feature

In [402]:
np.array([1,2,3]).shape[1]

IndexError: tuple index out of range

In [99]:
%timeit load_data(data_path)

1.06 ms ± 32 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
